# -----------------------------------------------------------------------------
# Test converting json to sql
# Author: Urs Roesch https://github.com/uroesch
# Version: 0.1.0 
# -----------------------------------------------------------------------------
name: create-sql

on:
  push:
    branches: 
    - postgresql

jobs:
  create-sql:
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: 
        - ubuntu-20.04
        - ubuntu-18.04
        - ubuntu-16.04
        ruby: 
        - 2.5
        - 2.6
        - 2.7
        - jruby
    continue-on-error: ${{ endsWith(matrix.ruby, 'head') || matrix.ruby == 'debug' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Setup ruby version
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: Check convert2psql
      run: bin/convert2psql > /dev/null
