# -----------------------------------------------------------------------------
# Sync forked master
# Author: Urs Roesch https://github.com/uroesch
# Version: 0.1.4 
# -----------------------------------------------------------------------------
name: sync-fork

on:
  push:
    branches:
      - workflow/*
  # Github prevents scheduled jobs from running in forks
  # Defies the purpos of this whole workflow but left in for nostalgia. 
  # schedule:
  #   - cron: '0 * 1-3 * *' # Run every hour on 1 to 3 day of month
  workflow_dispatch:

jobs:
  sync-fork:
    runs-on: ubuntu-latest
    steps:
      - name: env
        shell: bash
        run: |
          env | grep GITHUB || :

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: upstream
 
      - name: Sync with parent
        run: |2+
          function upstream_url() {
            curl \
              --silent \
              --header "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${GITHUB_REPOSITORY} | \
              jq -r .parent.clone_url
          }
          set -x
          git remote add upstream $(upstream_url)
          git fetch upstream
          if git rebase upstream/master | grep -q "is up to date"; then
            echo "Nothing to do"
          else
            git push origin upstream
          fi
